global:
  scrape_interval: 15s  # How often to scrape the targets

scrape_configs:
  - job_name: "memcache_service"  # Name for the group of targets
    static_configs:
      - targets: ["memcache_service:8081"]  # Target address for memcache_service

  - job_name: "shortener_service"  # Name for the group of targets (shortener microservice)
    static_configs:
      - targets: ["shortener_service:8080"]  # Target address for shortener_service
